import type { ExamType, Question } from "@mathprep/core";

import { SET_02_QUESTIONS } from "./amc8/set-02";
import { SET_03_QUESTIONS } from "./amc8/set-03";
import { SET_04_QUESTIONS } from "./amc8/set-04";
import { SET_05_QUESTIONS } from "./amc8/set-05";
import { SET_06_QUESTIONS } from "./amc8/set-06";
import { SET_07_QUESTIONS } from "./amc8/set-07";
import { AMC10_SET_01_QUESTIONS } from "./amc10/set-01";
import { AMC12_SET_01_QUESTIONS } from "./amc12/set-01";

export interface PracticeSet {
  examType: ExamType;
  setNumber: number;
  questions: Question[];
}

/**
 * Self-contained 25-question practice sets, generated by the author/verify
 * pipeline described in .claude/skills/author-questions/ and partitioned by
 * contest (amc8/, amc10/, amc12/). Every set follows its contest's shape:
 * positions 1-10 easy, 11-20 medium, 21-25 hard relative to that contest,
 * with an authentic topic distribution.
 */
export const PRACTICE_SETS: PracticeSet[] = [
  { examType: "amc8", setNumber: 2, questions: SET_02_QUESTIONS },
  { examType: "amc8", setNumber: 3, questions: SET_03_QUESTIONS },
  { examType: "amc8", setNumber: 4, questions: SET_04_QUESTIONS },
  { examType: "amc8", setNumber: 5, questions: SET_05_QUESTIONS },
  { examType: "amc8", setNumber: 6, questions: SET_06_QUESTIONS },
  { examType: "amc8", setNumber: 7, questions: SET_07_QUESTIONS },
  { examType: "amc10", setNumber: 1, questions: AMC10_SET_01_QUESTIONS },
  { examType: "amc12", setNumber: 1, questions: AMC12_SET_01_QUESTIONS },
];
